version: '3'
services:
  kafka:
    image: bitnami/kafka:3.1.0-debian-10-r31
    container_name: kafka-zookeeper-streams
    hostname: 127.0.0.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  zookeeper:
    image: bitnami/zookeeper:3.7.0-debian-10-r303
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper
      - ALLOW_ANONYMOUS_LOGIN=yes
